apiVersion: apps/v1
kind: Deployment
metadata: 
    name: apache-dep
    labels:
        app: apache
spec: 
    replicas: 3
    selector: 
        matchLabels: 
            app: apache
    template:
        metadata: 
              labels:
                  app: apache
        spec:
              containers: 
                - name: apche-pod
                  image: ubuntu/apache2
                  ports: 
                  - containerPort: 8080
              nodeSelector: 
                 label: node3
